import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { CalendarDays, PhoneCall, Shield, Upload } from 'lucide-react';
import './styles.css';

type ViewKey = 'dashboard' | 'monthly' | 'clients' | 'operators' | 'abandoned' | 'settings';
type Row = { id:string; callId:string; time:Date|null; day:string; month:string; from:string; to:string; direction:string; status:string; ringing:number; talking:number; wait:number; client:string; phone:string; operator:string };
type QueueCall = { callId:string; day:string; month:string; client:string; phone:string; service:'premium'|'forfait'|'autre'; treated:boolean; abandoned:boolean; wait:number; rows:Row[] };

const user = { email: 'sebastien.schmitt57@gmail.com', role: 'superadmin' };
const views: {key: ViewKey; label: string}[] = [
  { key: 'dashboard', label: 'Dashboard' },
  { key: 'monthly', label: 'Stats mensuelles' },
  { key: 'clients', label: 'Clients' },
  { key: 'operators', label: 'Operatrices' },
  { key: 'abandoned', label: 'Abandonnes' },
  { key: 'settings', label: 'Parametres' }
];

function norm(v:unknown){return String(v ?? '').trim()}
function sec(v:string){const p=norm(v).split(':').map(Number); if(p.length===3&&p.every(Number.isFinite)) return p[0]*3600+p[1]*60+p[2]; if(p.length===2&&p.every(Number.isFinite)) return p[0]*60+p[1]; return Number(norm(v).replace(',','.'))||0}
function fmt(n:number){const t=Math.max(0,Math.round(n||0)); const h=Math.floor(t/3600),m=Math.floor((t%3600)/60),s=t%60; return [h,m,s].map(x=>String(x).padStart(2,'0')).join(':')}
function parseDate(v:string){if(!v||v==='Totals')return null; const d=new Date(v); return Number.isNaN(d.getTime())?null:d}
function dayKey(d:Date|null){if(!d)return 'inconnu'; return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function inHours(d:Date|null){if(!d)return false; const v=d.getHours()+d.getMinutes()/60; return v>=8&&v<18}
function splitLine(line:string, sep:string){const out:string[]=[]; let cur='', q=false; for(let i=0;i<line.length;i++){const c=line[i],n=line[i+1]; if(c==='"'&&q&&n==='"'){cur+='"'; i++} else if(c==='"') q=!q; else if(c===sep&&!q){out.push(cur.trim().replace(/^"|"$/g,'')); cur=''} else cur+=c} out.push(cur.trim().replace(/^"|"$/g,'')); return out}
function parseCsv(text:string){const lines=text.split(/\r?\n/).filter(l=>l.trim()); if(lines.length<2)return [] as Record<string,string>[]; const sep=lines[0].includes(';')?';':','; const headers=splitLine(lines[0],sep); return lines.slice(1).map(line=>Object.fromEntries(splitLine(line,sep).map((cell,i)=>[headers[i]||`col${i}`,cell])))}
function phoneFrom(v:string){return norm(v).match(/0\d{6,}/)?.[0]||''}
function opName(v:string){const s=norm(v),l=s.toLowerCase(); if(!s||l.includes('client premium')||l.includes('client forfait')||l.includes('queue')||l.includes('repondeur')||l.includes('repon')) return ''; if(/\bA\d{1,3}\b/i.test(s)||!/\(\d+\)/.test(s)) return ''; return s.replace(/\(\d+\)/g,'').split(',').map(x=>x.trim()).filter(Boolean).reverse().join(' ')}
function clientFrom(r:Record<string,string>){const details=r['Call Activity Details']||''; const m=details.match(/A\d+\s+([^()]+)\s*\((0\d{6,})\)/i)||details.match(/:\s*([^()]+)\s*\((0\d{6,})\)/i); return norm(m?.[1])||norm(r.From)||'Client non identifie'}
function service(r:Row){const t=`${r.to} ${r.from}`.toLowerCase(); if(t.includes('client premium'))return 'premium' as const; if(t.includes('client forfait'))return 'forfait' as const; return 'autre' as const}
function mapRows(raw:Record<string,string>[]):Row[]{return raw.map((r,i)=>{const time=parseDate(r['Call Time']); const ringing=sec(r.Ringing), talking=sec(r.Talking); return {id:`${i}-${r['Call ID']||''}`,callId:norm(r['Call ID'])||String(i),time,day:dayKey(time),month:dayKey(time).slice(0,7),from:norm(r.From),to:norm(r.To),direction:norm(r.Direction),status:norm(r.Status),ringing,talking,wait:Math.max(ringing,talking),client:clientFrom(r),phone:phoneFrom(r.From)||phoneFrom(r['Call Activity Details']||''),operator:opName(r.To)||opName(r.From)||'Non attribue'}}).filter(r=>r.time)}
function isQueue(r:Row){return r.direction.toLowerCase()==='inbound queue'} function isWaiting(r:Row){return r.status.toLowerCase()==='waiting'} function isUnanswered(r:Row){return r.status.toLowerCase()==='unanswered'} function isAnswered(r:Row){return r.status.toLowerCase()==='answered'} function isInbound(r:Row){return r.direction.toLowerCase()==='inbound'} function isOutbound(r:Row){return r.direction.toLowerCase()==='outbound'} function isInternal(r:Row){return r.direction.toLowerCase()==='internal'}
function buildQueue(rows:Row[]){const map=new Map<string,QueueCall>(); for(const r of rows){if(!inHours(r.time)||!isQueue(r)||(!isWaiting(r)&&!isUnanswered(r)))continue; const q=map.get(r.callId)||{callId:r.callId,day:r.day,month:r.month,client:r.client,phone:r.phone,service:service(r),treated:false,abandoned:false,wait:0,rows:[]}; if(r.client&&r.client!=='Client non identifie')q.client=r.client; if(r.phone&&!q.phone)q.phone=r.phone; if(q.service==='autre')q.service=service(r); q.wait=Math.max(q.wait,r.wait); if(isWaiting(r))q.treated=true; if(isUnanswered(r))q.abandoned=true; q.rows.push(r); map.set(r.callId,q)} return [...map.values()]}
function rowsOf(calls:QueueCall[]){return calls.flatMap(c=>c.rows)}
function summarize(rows:Row[]){const business=rows.filter(r=>inHours(r.time)); const queue=buildQueue(business); const treated=queue.filter(q=>q.treated); const abandoned=queue.filter(q=>!q.treated&&q.abandoned); const total=treated.length+abandoned.length; return {business,queue,treated,abandoned,total,waitingNow:0,maxWait:queue.reduce((m,q)=>Math.max(m,q.wait),0),premiumAbandoned:abandoned.filter(q=>q.service==='premium').length,internal:business.filter(r=>isInternal(r)&&isAnswered(r)).length,outbound:business.filter(r=>isOutbound(r)&&isAnswered(r)&&r.talking>=10).length,answerRate:total?Math.round(treated.length/total*1000)/10:0,abandonRate:total?Math.round(abandoned.length/total*1000)/10:0}}
function groupBy<T>(items:T[], fn:(item:T)=>string){const m=new Map<string,T[]>(); for(const item of items)m.set(fn(item),[...(m.get(fn(item))||[]),item]); return m}

function App(){
  const [rows,setRows]=useState<Row[]>([]); const [periodMode,setPeriodMode]=useState('month'); const [client,setClient]=useState('all'); const [operator,setOperator]=useState('all'); const [detail,setDetail]=useState<Row[]|null>(null); const [activeView,setActiveView]=useState<ViewKey>('dashboard');
  const clients=useMemo(()=>[...new Set(rows.map(r=>r.client))].filter(Boolean).sort(),[rows]);
  const operators=useMemo(()=>[...new Set(rows.map(r=>r.operator))].filter(o=>o&&o!=='Non attribue').sort(),[rows]);
  const filtered=useMemo(()=>rows.filter(r=>(client==='all'||r.client===client)&&(operator==='all'||r.operator===operator)),[rows,client,operator]);
  const stats=useMemo(()=>summarize(filtered),[filtered]);
  const daily=useMemo(()=>[...groupBy(stats.queue,q=>q.day).entries()].sort().map(([day,list])=>({day:day.slice(5),appels:list.length,traites:list.filter(q=>q.treated).length,abandonnes:list.filter(q=>!q.treated&&q.abandoned).length})),[stats.queue]);
  const monthly=useMemo(()=>[...groupBy(stats.queue,q=>q.month).entries()].sort().map(([month,list])=>({month,appels:list.length,traites:list.filter(q=>q.treated).length,abandonnes:list.filter(q=>!q.treated&&q.abandoned).length})),[stats.queue]);
  const byClient=useMemo(()=>[...groupBy(stats.queue,q=>q.client).entries()].map(([label,list])=>({label,total:list.length,treated:list.filter(q=>q.treated).length,abandoned:list.filter(q=>!q.treated&&q.abandoned).length,rows:rowsOf(list)})).sort((a,b)=>b.total-a.total),[stats.queue]);
  const byOperator=useMemo(()=>[...groupBy(filtered.filter(r=>inHours(r.time)&&isInbound(r)&&isAnswered(r)&&r.operator!=='Non attribue'),r=>r.operator).entries()].map(([label,list])=>({label,total:list.length,avg:list.length?Math.round(list.reduce((s,r)=>s+r.talking,0)/list.length):0,rows:list})).sort((a,b)=>b.total-a.total),[filtered]);
  async function handleFile(file:File){setRows(mapRows(parseCsv(await file.text())))}
  return <main className="appShell"><aside className="sidebar"><div className="brand">Nexus <span>V2</span></div><div className="userBox"><Shield size={18}/>{user.email}<small>{user.role}</small></div><nav>{views.map(v=><button key={v.key} className={activeView===v.key?'activeNav':''} onClick={()=>setActiveView(v.key)}>{v.label}</button>)}</nav></aside><section className="content"><header className="topbar"><div><h1>{views.find(v=>v.key===activeView)?.label}</h1><p>Base 3CX officielle : 08h00-18h00, Inbound Queue + Waiting / Unanswered.</p></div><label className="uploadButton"><Upload size={18}/> Importer export 3CX<input type="file" accept=".csv,text/csv" onChange={e=>e.target.files?.[0]&&handleFile(e.target.files[0])}/></label></header><section className="filters"><label>Periode<select value={periodMode} onChange={e=>setPeriodMode(e.target.value)}><option value="day">Jour</option><option value="week">Semaine</option><option value="month">Mois</option><option value="quarter">Trimestre</option><option value="year">Annee</option></select></label><label>Client<select value={client} onChange={e=>setClient(e.target.value)}><option value="all">Tous</option>{clients.map(c=><option key={c}>{c}</option>)}</select></label><label>Operatrice<select value={operator} onChange={e=>setOperator(e.target.value)}><option value="all">Toutes</option>{operators.map(o=><option key={o}>{o}</option>)}</select></label><div className="periodHint"><CalendarDays size={16}/> Les boutons de gauche pilotent maintenant les vues.</div></section>{activeView==='dashboard'&&<Dashboard stats={stats} filtered={filtered} daily={daily} monthly={monthly} setDetail={setDetail}/>} {activeView==='monthly'&&<Monthly monthly={monthly}/>} {activeView==='clients'&&<Panel title="Analyse clients"><Table rows={byClient.slice(0,50)} columns={[["label","Client"],["total","Total file"],["treated","Traites"],["abandoned","Abandonnes"]]} onOpen={r=>setDetail(r.rows)}/></Panel>} {activeView==='operators'&&<Panel title="Analyse operatrices"><Table rows={byOperator.slice(0,50)} columns={[["label","Operatrice"],["total","Decroches"],["avg","Duree moy. s"]]} onOpen={r=>setDetail(r.rows)}/></Panel>} {activeView==='abandoned'&&<Panel title="Appels abandonnes"><Table rows={stats.abandoned.map(q=>({label:q.client,phone:q.phone,service:q.service,wait:fmt(q.wait),rows:q.rows}))} columns={[["label","Client"],["phone","Telephone"],["service","Type"],["wait","Attente"]]} onOpen={r=>setDetail(r.rows)}/></Panel>} {activeView==='settings'&&<Settings/>} {!rows.length&&<section className="emptyState"><PhoneCall size={32}/><h2>Importer un export 3CX pour demarrer</h2><p>La V2 analyse le fichier immediatement.</p></section>}</section>{detail&&<Detail rows={detail} onClose={()=>setDetail(null)}/>}</main>
}
function Dashboard({stats,filtered,daily,monthly,setDetail}:{stats:ReturnType<typeof summarize>;filtered:Row[];daily:any[];monthly:any[];setDetail:(rows:Row[])=>void}){return <><section className="cards"><Stat title="En attente d'appels" value={stats.waitingNow} onClick={()=>setDetail([])}/><Stat title="Appels traites" value={stats.treated.length} suffix={`${stats.answerRate}%`} onClick={()=>setDetail(rowsOf(stats.treated))}/><Stat title="Appels abandonnes" value={stats.abandoned.length} suffix={`${stats.abandonRate}%`} tone="danger" onClick={()=>setDetail(rowsOf(stats.abandoned))}/><Stat title="Attente la plus longue" value={fmt(stats.maxWait)} onClick={()=>setDetail(rowsOf(stats.queue.filter(q=>q.wait===stats.maxWait)))}/><Stat title="Total file" value={stats.total} onClick={()=>setDetail(rowsOf(stats.queue))}/><Stat title="Premium abandonnes" value={stats.premiumAbandoned} tone="warning" onClick={()=>setDetail(rowsOf(stats.abandoned.filter(q=>q.service==='premium')))}/><Stat title="Internes" value={stats.internal} onClick={()=>setDetail(filtered.filter(r=>inHours(r.time)&&isInternal(r)&&isAnswered(r)))}/><Stat title="Sortants" value={stats.outbound} onClick={()=>setDetail(filtered.filter(r=>inHours(r.time)&&isOutbound(r)&&isAnswered(r)&&r.talking>=10))}/></section><section className="grid2"><Panel title="Courbe par jour"><ResponsiveContainer width="100%" height={280}><LineChart data={daily}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="day"/><YAxis/><Tooltip/><Line type="monotone" dataKey="appels"/><Line type="monotone" dataKey="traites"/><Line type="monotone" dataKey="abandonnes"/></LineChart></ResponsiveContainer></Panel><Panel title="Vue annuelle / mensuelle"><ResponsiveContainer width="100%" height={280}><BarChart data={monthly}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="month"/><YAxis/><Tooltip/><Bar dataKey="appels"/><Bar dataKey="abandonnes"/></BarChart></ResponsiveContainer></Panel></section></>}
function Monthly({monthly}:{monthly:any[]}){return <Panel title="Stats mensuelles"><ResponsiveContainer width="100%" height={360}><BarChart data={monthly}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="month"/><YAxis/><Tooltip/><Bar dataKey="appels"/><Bar dataKey="traites"/><Bar dataKey="abandonnes"/></BarChart></ResponsiveContainer></Panel>}
function Settings(){return <Panel title="Parametres"><p>Gestion utilisateurs, droits par vue et connexion web seront branches a la base PostgreSQL dans l'etape suivante.</p></Panel>}
function Stat({title,value,suffix,tone,onClick}:{title:string;value:number|string;suffix?:string;tone?:'danger'|'warning';onClick:()=>void}){return <button className={`statCard ${tone||''}`} onClick={onClick}><span>{title}</span><b>{typeof value==='number'?value.toLocaleString('fr-FR'):value}</b>{suffix&&<small>{suffix}</small>}</button>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="panel"><h2>{title}</h2>{children}</section>}
function Table({rows,columns,onOpen}:{rows:any[];columns:[string,string][];onOpen:(row:any)=>void}){return <div className="tableWrap"><table><thead><tr>{columns.map(([,l])=><th key={l}>{l}</th>)}<th>Detail</th></tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{columns.map(([k])=><td key={k}>{r[k]}</td>)}<td><button className="small" onClick={()=>onOpen(r)}>Ouvrir</button></td></tr>)}</tbody></table></div>}
function Detail({rows,onClose}:{rows:Row[];onClose:()=>void}){return <div className="modalBackdrop"><div className="modal"><header><h2>Detail des appels</h2><button onClick={onClose}>Fermer</button></header><div className="tableWrap"><table><thead><tr><th>Date</th><th>Client</th><th>Operatrice</th><th>Telephone</th><th>Direction</th><th>Statut</th><th>Attente</th><th>Duree</th></tr></thead><tbody>{rows.slice(0,500).map(r=><tr key={r.id}><td>{r.time?.toLocaleString('fr-FR')||'-'}</td><td>{r.client}</td><td>{r.operator}</td><td>{r.phone}</td><td>{r.direction}</td><td>{r.status}</td><td>{fmt(r.wait)}</td><td>{fmt(r.talking)}</td></tr>)}</tbody></table></div></div></div>}

createRoot(document.getElementById('root')!).render(<App/>);
